name: PR Comment

on:
  pull_request_target:
    types:
      - opened

permissions:
  pull_requests: write

jobs:
  PR-Comment:
    uses: jeffvg/workflows/.github/workflows/pr-comment.yml@dev