name: PR Labeler

on:
  pull_request_target:
    types:
      - opened

permissions:
  pull-requests: write

jobs:
  PR_Labeler:
    uses: jeffvg/mui5-react17/.github/workflows/pr-labeler.yml@master