name: blui-labeler

on:
  pull_request_target:
    types:
      - opened

permissions:
  pull-requests: write
  contents: read

jobs:
  pr-labeler:
    uses: jeffvg/workflows/.github/workflows/blui-labeler.yml@dev
    secrets: inherit