name: PR Labeler

on: [push, pull_request]

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger reusable workflow
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: jeffvg/mui5-react17/.github/workflows/pr-labeler.yml@dev
        event-type: run-workflow
        client-payload: {}