name: PR Labeler

on:
  pull_request_target:
    types:
      - opened

permissions:
  pull_requests: write

jobs:
  pr-labeler:
    uses: jeffvg/workflows/.github/workflows/pr-labeler.yml@dev