name: PR Labeler

on:
  pull_request_target:
    types:
      - opened

permissions:
  pull-requests: write
  contents: read

jobs:
  pr-labeler:
    uses: jeffvg/mui5-react17/.github/workflows/pr-labeler.yml@master
    with:
      configuration-path: .github/pr-labeler.yml
    secrets: inherit